CREATE TABLE IF NOT EXISTS "recommended_colours" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "recommended_colours_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"palette_id" integer NOT NULL,
	"name" varchar(255) NOT NULL,
	"hex" varchar(7) NOT NULL,
	"reason" text NOT NULL
);
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "recommended_colours" ADD CONSTRAINT "recommended_colours_palette_id_palette_id_fk" FOREIGN KEY ("palette_id") REFERENCES "public"."palette"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
ALTER TABLE "palette" DROP COLUMN IF EXISTS "colours";