DO $$ BEGIN
 CREATE TYPE "public"."gender" AS ENUM('male', 'female');
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "celebrities" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "celebrities_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"palette_id" integer NOT NULL,
	"name" varchar(255) NOT NULL,
	"gender" "gender" NOT NULL,
	"reason" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "colors" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "colors_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"palette_id" integer NOT NULL,
	"name" varchar(255) NOT NULL,
	"hex" varchar(7) NOT NULL,
	"percentage" numeric(5, 2),
	"is_recommended" boolean DEFAULT false
);
--> statement-breakpoint
DROP TABLE "recommended_colours";--> statement-breakpoint
ALTER TABLE "palette" ALTER COLUMN "sub_season" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "palette" ADD COLUMN "percentage" numeric(5, 2);--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "celebrities" ADD CONSTRAINT "celebrities_palette_id_palette_id_fk" FOREIGN KEY ("palette_id") REFERENCES "public"."palette"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "colors" ADD CONSTRAINT "colors_palette_id_palette_id_fk" FOREIGN KEY ("palette_id") REFERENCES "public"."palette"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
